# Only 1 location can be active at a time. Comment out the one not in use. If 2 locations are active, the program will fetch the first.
locations:
  - bond_crescent
  # - corinthian_drive

price_per_court: 27

# Time is in 24-hour format.
# If a day is set to null, no booking will be made on that day.
# If a day has a start and end time, a booking will be made within that time range.
# If a day has a start time and no end time, the end time will default to "23:00"
# If a day has no start time and an end time, the start time will default to "06:00"
schedule:
  monday:
    start: "19:00"
    end: "21:00"
  tuesday: null
  wednesday:
    start: "19:00"
    end: "21:00"
  thursday:
    start: "19:00"
    end: "21:00"
  friday:
    start: "19:00"
    end: "21:00"
  saturday:
    start: "12:00"
    end: "19:00"
  sunday:
    start: "12:00"
    end: "19:00"
