# Only 1 location can be active at a time. Comment out the one not in use. If 2 locations are active, the program will fetch the first.
# This is the preferred fallback location in case the location specified in the schedule is invalid or not provided.
locations:
  - bond_crescent
  - corinthian_drive

price_per_court: 27

# Time must be in "HH:MM" 24-hour format (i.e. "09:00", not "9:00")
# If a day is set to null, no booking will be made on that day.
# If a day has a start and end time, a booking will be made within that time range.
# If a day has a start time and no end time, the end time will default to "23:00"
# If a day has no start time and an end time, the start time will default to "06:00"
# 3 variables per day: start, end, location
# Location is not mandatory. If not provided, the location listed in the 'locations' section will be used.
schedule:
  monday: null
  tuesday: null
  wednesday:
    start: "19:00"
    end: "21:00"
  thursday: null
  friday: null
  saturday: null
  sunday:
    start: "12:00"
    end: "19:00"
    location: "bond_crescent"
