locations:
  # - corinthian_drive
  - bond_crescent

price_per_court: 27

schedule:
  monday:
    start: "19:00"
    end: "21:00"
  tuesday: null
  wednesday:
    start: "19:00"
    end: "21:00"
  thursday: null
  friday:
    start: "19:00"
    end: "21:00"
  saturday:
    start: "12:00"
    end: "19:00"
  sunday:
    start: "12:00"
    end: "19:00"
